name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: 'readme.md'
          max_post_count: '3'
          feed_list: 'https://medium.com/feed/@uk960214'
